import { 
  Organization,
  FrameworkInfo, 
  EvidenceItem, 
  ControlItem, 
  GapItem, 
  ReviewQueueItem, 
  AuditTrailLog, 
  UserProfile, 
  NotificationItem 
} from '../types';

export const mockOrganizations: Organization[] = [
  {
    id: 'org-acme',
    name: 'Acme Technologies Inc.',
    slug: 'acme-tech',
    industry: 'B2B SaaS / Infrastructure',
    plan: 'Enterprise',
    auditPeriod: 'Q3 2026 Audit Window',
    activeFrameworks: ['iso-27001', 'soc-2', 'pci-dss', 'dpdp'],
  },
  {
    id: 'org-cybershield',
    name: 'CyberShield Cloud Solutions',
    slug: 'cybershield',
    industry: 'Cloud Cybersecurity & SecOps',
    plan: 'Growth',
    auditPeriod: 'SOC 2 Annual Audit Cycle',
    activeFrameworks: ['iso-27001', 'soc-2'],
  },
  {
    id: 'org-nexus',
    name: 'Nexus Health Systems',
    slug: 'nexus-health',
    industry: 'Healthcare Data Fiduciary',
    plan: 'Enterprise',
    auditPeriod: 'DPDP & ISO Compliance Cycle',
    activeFrameworks: ['iso-27001', 'dpdp'],
  },
];

export const mockUsers: UserProfile[] = [
  {
    id: 'usr-1',
    name: 'Aarav Mehta',
    email: 'aarav.mehta@acme.com',
    role: 'ciso',
    roleTitle: 'Enterprise CISO',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-acme',
    organizationName: 'Acme Technologies Inc.',
    lastActive: 'Just now',
    status: 'active',
  },
  {
    id: 'usr-2',
    name: 'David Chen, CPA',
    email: 'david.chen@auditfirm-partner.com',
    role: 'auditor',
    roleTitle: 'Lead External Auditor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-acme',
    organizationName: 'Acme Technologies Inc.',
    lastActive: '12 mins ago',
    status: 'active',
  },
  {
    id: 'usr-3',
    name: 'Priya Sharma',
    email: 'priya.sharma@acme.com',
    role: 'compliance_team',
    roleTitle: 'Head of GRC & Security Operations',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-acme',
    organizationName: 'Acme Technologies Inc.',
    lastActive: '1 hour ago',
    status: 'active',
  },
  {
    id: 'usr-viewer',
    name: 'Ananya Roy',
    email: 'ananya.roy@acme.com',
    role: 'viewer',
    roleTitle: 'Compliance Observer (Read-Only)',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-acme',
    organizationName: 'Acme Technologies Inc.',
    lastActive: '2 hours ago',
    status: 'active',
  },
  // CyberShield Users
  {
    id: 'usr-4',
    name: 'Elena Rostova',
    email: 'elena@cybershield.io',
    role: 'ciso',
    roleTitle: 'Chief Security Officer',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-cybershield',
    organizationName: 'CyberShield Cloud Solutions',
    lastActive: '20 mins ago',
    status: 'active',
  },
  // Nexus Health Users
  {
    id: 'usr-5',
    name: 'Dr. Vikram Patel',
    email: 'vikram.patel@nexushealth.org',
    role: 'ciso',
    roleTitle: 'Chief Privacy & Data Protection Officer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-nexus',
    organizationName: 'Nexus Health Systems',
    lastActive: '5 mins ago',
    status: 'active',
  }
];

export const mockFrameworks: FrameworkInfo[] = [
  {
    id: 'iso-27001',
    name: 'ISO/IEC 27001:2022',
    code: 'ISO 27001',
    version: '2022 Revision (v2.1)',
    description: 'International standard for Information Security Management Systems (ISMS). Focuses on risk analysis, asset management, and access controls.',
    totalControls: 146,
    coveredControls: 114,
    readinessPercentage: 78,
    pendingReviews: 4,
    openGaps: 3,
    status: 'On Track',
    lastAuditDate: '2026-08-15',
  },
  {
    id: 'soc-2',
    name: 'SOC 2 Type II',
    code: 'SOC 2',
    version: '2024 Trust Services Criteria (v4.0)',
    description: 'AICPA framework evaluating controls relevant to Security, Availability, Processing Integrity, Confidentiality, and Privacy over a 6-month window.',
    totalControls: 87,
    coveredControls: 62,
    readinessPercentage: 71,
    pendingReviews: 8,
    openGaps: 4,
    status: 'On Track',
    lastAuditDate: '2026-06-30',
  },
  {
    id: 'pci-dss',
    name: 'PCI DSS v4.0',
    code: 'PCI DSS',
    version: 'v4.0 Standard Specification',
    description: 'Payment Card Industry Data Security Standard covering technical and operational requirements for entities storing, processing, or transmitting cardholder data.',
    totalControls: 65,
    coveredControls: 42,
    readinessPercentage: 64,
    pendingReviews: 4,
    openGaps: 3,
    status: 'Attention Needed',
    lastAuditDate: '2026-04-12',
  },
  {
    id: 'dpdp',
    name: 'Digital Personal Data Protection Act (DPDP)',
    code: 'DPDP Act',
    version: '2023 India Compliance (v1.0)',
    description: 'Statutory regulations for processing digital personal data, data fiduciary obligations, consent architecture, and data principal rights.',
    totalControls: 34,
    coveredControls: 28,
    readinessPercentage: 82,
    pendingReviews: 2,
    openGaps: 1,
    status: 'On Track',
    lastAuditDate: '2026-07-22',
  },
];

export const mockEvidence: EvidenceItem[] = [
  // Org 1: Acme Technologies
  {
    id: 'ev-101',
    organizationId: 'org-acme',
    name: 'AWS IAM Role & Least Privilege Configuration',
    fileName: 'AWS_IAM_Identity_Store_Config_2026.json',
    fileType: 'json',
    fileSize: '4.2 MB',
    fileHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    version: 'v2.1',
    expiryDate: '2027-09-20',
    owner: 'Priya Sharma',
    ownerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    frameworks: ['iso-27001', 'soc-2'],
    mappedControlIds: ['ISO-A.9.2.1', 'SOC2-CC6.1'],
    processingStatus: 'mapped',
    aiConfidence: 96,
    aiReasoning: 'JSON policy document contains explicit JSON statements enforcing MFA, temporary role assumption via STS, and automated IAM session termination after 12 hours.',
    aiModelInfo: {
      model: 'Pramana LLM RAG Pipeline',
      modelVersion: 'v4.2',
      promptVersion: 'v2.1-compliance-extract',
      runId: 'run-8921-iam',
    },
    extractedTextExcerpt: '"Statement": [{"Effect": "Allow", "Action": ["sts:AssumeRole"], "Resource": "*", "Condition": {"Bool": {"aws:MultiFactorAuthPresent": "true"}}}, {"Sid": "MaxSessionLength", "MaxSessionDuration": 43200}]',
    citations: [
      { page: 1, section: 'IAM Policy Statement 3', text: 'aws:MultiFactorAuthPresent = true' },
      { page: 2, section: 'STS Session Duration', text: 'MaxSessionDuration: 43200 seconds' }
    ],
    uploadDate: '2026-09-20 10:14 AM',
    lastUpdated: '2026-09-22 02:30 PM',
    decisionType: 'human_decision',
    auditorDecision: 'approved',
    auditorName: 'David Chen, CPA',
    auditorNotes: 'Verified IAM configurations against zero-trust policy. MFA enforced across production root accounts.',
    auditorDecisionDate: '2026-09-22 02:30 PM',
    securityLevel: 'Confidential',
  },
  {
    id: 'ev-102',
    organizationId: 'org-acme',
    name: 'Okta Adaptive MFA & SSO Enforcement Audit Export',
    fileName: 'Okta_MFA_Enforcement_Policy_v4.pdf',
    fileType: 'pdf',
    fileSize: '12.8 MB',
    fileHash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
    version: 'v4.0',
    expiryDate: '2027-03-15',
    owner: 'Priya Sharma',
    ownerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    frameworks: ['iso-27001', 'soc-2', 'pci-dss'],
    mappedControlIds: ['ISO-A.9.4.2', 'SOC2-CC6.2', 'PCI-8.3.1'],
    processingStatus: 'needs_review',
    aiConfidence: 92,
    aiReasoning: 'Okta configuration screenshot and policy text demonstrate universal WebAuthn FIDO2 requirement for all employee accounts and VPN endpoints.',
    aiModelInfo: {
      model: 'Pramana LLM RAG Pipeline',
      modelVersion: 'v4.2',
      promptVersion: 'v2.1-compliance-extract',
      runId: 'run-9104-okta',
    },
    extractedTextExcerpt: 'Rule #1: Enforce Multi-Factor Authentication (MFA) on every sign-in attempt. Allowed Authenticators: Okta Verify Push, FIDO2 WebAuthn Key.',
    citations: [
      { page: 4, section: 'Authentication Policies', text: 'Allowed Authenticators: FIDO2 WebAuthn Key' },
      { page: 7, section: 'Network Perimeter Access', text: 'VPN challenge step-up required' }
    ],
    missingEvidenceList: ['Quarterly Service Account Exemption Approval Matrix'],
    uploadDate: '2026-09-23 09:15 AM',
    lastUpdated: '2026-09-23 09:15 AM',
    decisionType: 'pending_human_review',
    securityLevel: 'Confidential',
  },
  {
    id: 'ev-103',
    organizationId: 'org-acme',
    name: 'Q3 Enterprise Penetration Testing Report 2026',
    fileName: 'Annual_Penetration_Testing_Report_Q3.pdf',
    fileType: 'pdf',
    fileSize: '24.5 MB',
    fileHash: 'c7d24a9e52c8091a1d999037c86720272b14467554901b0728c3125d0e2e9ef4',
    version: 'v1.0',
    expiryDate: '2027-09-14',
    owner: 'Aarav Mehta',
    ownerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    frameworks: ['iso-27001', 'soc-2', 'pci-dss'],
    mappedControlIds: ['ISO-A.12.6.1', 'SOC2-CC7.2', 'PCI-11.3.2'],
    processingStatus: 'needs_review',
    aiConfidence: 89,
    aiReasoning: 'External grey-box penetration test conducted by Bishop Fox CREST certified auditors. Zero critical/high vulnerability findings remaining.',
    extractedTextExcerpt: 'Executive Summary: Bishop Fox conducted penetration testing against Acme Core API. All 3 initial medium findings were verified remediated on Sept 14, 2026.',
    citations: [
      { page: 2, section: 'Executive Summary', text: 'Zero remaining critical or high vulnerabilities' },
      { page: 18, section: 'Re-test Attestation', text: 'Verified remediated on Sept 14, 2026' }
    ],
    uploadDate: '2026-09-22 04:45 PM',
    lastUpdated: '2026-09-22 04:45 PM',
    decisionType: 'pending_human_review',
    securityLevel: 'Confidential',
  },

  // Org 2: CyberShield Cloud
  {
    id: 'ev-201',
    organizationId: 'org-cybershield',
    name: 'CyberShield Zero Trust Perimeter Architecture Document',
    fileName: 'CyberShield_ZeroTrust_Architecture_v2.pdf',
    fileType: 'pdf',
    fileSize: '15.4 MB',
    fileHash: 'f482a4918c502b1849a941e739487c50a12b489a',
    version: 'v2.0',
    owner: 'Elena Rostova',
    ownerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    frameworks: ['iso-27001', 'soc-2'],
    mappedControlIds: ['ISO-A.9.2.1', 'SOC2-CC6.1'],
    processingStatus: 'mapped',
    aiConfidence: 97,
    aiReasoning: 'Pramana AI confirmed Cloudflare Access zero-trust microsegmentation and wireguard mesh tunnel policy.',
    extractedTextExcerpt: 'Policy 1: All internal Kubernetes management ports restricted to Cloudflare Zero Trust Access gateway with mTLS certificate authentication.',
    citations: [
      { page: 3, section: 'Zero Trust Network Architecture', text: 'mTLS certificate authentication enforced' }
    ],
    uploadDate: '2026-09-18 11:00 AM',
    lastUpdated: '2026-09-19 03:20 PM',
    decisionType: 'human_decision',
    auditorDecision: 'approved',
    auditorName: 'David Chen, CPA',
    securityLevel: 'Confidential',
  },

  // Org 3: Nexus Health
  {
    id: 'ev-301',
    organizationId: 'org-nexus',
    name: 'Nexus Health Patient EHR Data Pseudonymization Policy',
    fileName: 'Nexus_EHR_DPDP_Consent_Audit.pdf',
    fileType: 'pdf',
    fileSize: '8.9 MB',
    fileHash: '39481a5091b2c48192d19e487102b3941',
    version: 'v1.0',
    owner: 'Dr. Vikram Patel',
    ownerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    frameworks: ['dpdp', 'iso-27001'],
    mappedControlIds: ['DPDP-SEC8', 'DPDP-SEC6'],
    processingStatus: 'needs_review',
    aiConfidence: 94,
    aiReasoning: 'Pramana AI analyzed DPDP Data Fiduciary Obligations. Automated AES-256 field-level encryption for patient Aadhaar and medical records.',
    extractedTextExcerpt: 'Section 3.1 Personal Health Data Encryption: All FHIR API endpoints enforce tokenized field encryption with HSM customer-managed keys.',
    citations: [
      { page: 5, section: 'Data Pseudonymization Pipeline', text: 'HSM customer-managed key rotation' }
    ],
    uploadDate: '2026-09-24 09:30 AM',
    lastUpdated: '2026-09-24 09:30 AM',
    decisionType: 'pending_human_review',
    securityLevel: 'Confidential',
  }
];

export const mockControls: ControlItem[] = [
  // Org 1: Acme
  {
    id: 'ISO-A.9.2.1',
    organizationId: 'org-acme',
    code: 'A.9.2.1',
    title: 'User Registration & De-registration',
    description: 'A formal user registration and de-registration process shall be implemented to enable granting and revoking access to all information systems and services.',
    objective: 'Ensure logical access rights are assigned and revoked in accordance with authorized access control policy.',
    requirementText: 'Organizations must maintain documented procedures for onboarding and offboarding employees, contractors, and third-party users within 24 hours of status change.',
    assessmentMethod: 'Automated IAM Configuration Audit & HR Deprovisioning Log Verification',
    framework: 'iso-27001',
    frameworkVersion: '2022 Revision',
    category: 'Access Control',
    coverageState: 'full',
    mappedEvidenceCount: 2,
    evidenceIds: ['ev-101', 'ev-102'],
    aiConfidence: 96,
    aiExplanation: 'Automated IAM role configuration and Okta SSO logs confirm synchronized user lifecycle provisioning and immediate session invalidation on offboarding.',
    reviewStatus: 'Approved',
    auditorDecision: 'approved',
    auditorName: 'David Chen, CPA',
    auditorDecisionDate: '2026-09-22 02:30 PM',
    auditorComments: ['Verified user provisioning workflow. Auto-deprovisioning verified against HR system integration.'],
    gapsCount: 0,
  },
  {
    id: 'SOC2-CC6.1',
    organizationId: 'org-acme',
    code: 'CC6.1',
    title: 'Logical Access Security Controls',
    description: 'The entity implements logical access security software, infrastructure, and architectures to protect information assets from unauthorized access.',
    objective: 'Prevent unauthorized logical access to customer data and infrastructure endpoints.',
    requirementText: 'Logical access controls must enforce role-based access control (RBAC), multi-factor authentication (MFA), and zero-trust principles across all environment endpoints.',
    assessmentMethod: 'Okta Adaptive MFA Export & AWS STS STS AssumeRole Policy Inspection',
    framework: 'soc-2',
    frameworkVersion: '2024 Trust Services Criteria',
    category: 'Common Criteria - Logical Access',
    coverageState: 'full',
    mappedEvidenceCount: 2,
    evidenceIds: ['ev-101', 'ev-102'],
    aiConfidence: 94,
    aiExplanation: 'AWS IAM policy and Okta MFA exports demonstrate 100% MFA coverage across production and administrative accounts.',
    reviewStatus: 'Pending Review',
    gapsCount: 0,
  },

  // Org 2: CyberShield
  {
    id: 'ISO-A.9.2.1',
    organizationId: 'org-cybershield',
    code: 'A.9.2.1',
    title: 'Zero Trust Access Provisioning',
    description: 'CyberShield Zero Trust identity mesh configuration.',
    requirementText: 'Enforce mTLS certificate validation on all remote Kubernetes management nodes.',
    framework: 'iso-27001',
    frameworkVersion: '2022 Revision',
    category: 'Access Control',
    coverageState: 'full',
    mappedEvidenceCount: 1,
    evidenceIds: ['ev-201'],
    aiConfidence: 97,
    aiExplanation: 'Cloudflare Zero Trust Access mesh verified compliant.',
    reviewStatus: 'Approved',
    auditorDecision: 'approved',
    auditorName: 'David Chen, CPA',
    auditorComments: ['mTLS architecture verified.'],
    gapsCount: 0,
  },

  // Org 3: Nexus Health
  {
    id: 'DPDP-SEC8',
    organizationId: 'org-nexus',
    code: 'Section 8(4)',
    title: 'Data Fiduciary EHR Safeguards',
    description: 'Patient Health Data Fiduciary protection under DPDP Act 2023.',
    requirementText: 'Enforce HSM tokenized field-level encryption for all healthcare records.',
    framework: 'dpdp',
    frameworkVersion: '2023 India Compliance',
    category: 'Data Fiduciary Obligations',
    coverageState: 'full',
    mappedEvidenceCount: 1,
    evidenceIds: ['ev-301'],
    aiConfidence: 94,
    aiExplanation: 'FHIR API tokenization verified.',
    reviewStatus: 'Pending Review',
    gapsCount: 0,
  }
];

export const mockGaps: GapItem[] = [
  // Org 1: Acme
  {
    id: 'gap-301',
    organizationId: 'org-acme',
    title: 'Unencrypted Staging Storage Buckets (SSE-S3 vs KMS)',
    framework: 'iso-27001',
    controlId: 'ISO-A.10.1.1',
    severity: 'high',
    owner: 'Priya Sharma',
    dueDate: '2026-10-05',
    status: 'open',
    identifiedDate: '2026-09-21',
    whyIdentified: 'AI evidence analysis of S3_Bucket_Encryption_Policy_Export.json identified 2 buckets (`acme-dev-temp-logs` and `acme-test-cache`) configured without KMS customer-managed keys.',
    missingInfo: 'KMS Key Policy JSON binding and bucket encryption override confirmation.',
    recommendedAction: 'Update Terraform script to attach AWS KMS CMK key ARN `arn:aws:kms:us-east-1:123456789012:key/cmk-production-sec` to staging buckets.',
    relatedEvidenceIds: ['ev-104'],
  },
  {
    id: 'gap-302',
    organizationId: 'org-acme',
    title: 'Missing Quarterly Firewall Rule Review Log for PCI CDE',
    framework: 'pci-dss',
    controlId: 'PCI-1.2.1',
    severity: 'critical',
    owner: 'Aarav Mehta',
    dueDate: '2026-09-30',
    status: 'in_remediation',
    identifiedDate: '2026-09-15',
    whyIdentified: 'PCI DSS v4.0 Requirement 1.2.1 requires mandatory quarterly firewall and security group rule reviews.',
    missingInfo: 'Q3 2026 Network Security Group & AWS Security Group approval matrix.',
    recommendedAction: 'Export AWS Security Group rules and submit Network Lead review sign-off log for Q3.',
    relatedEvidenceIds: [],
  },

  // Org 2: CyberShield
  {
    id: 'gap-401',
    organizationId: 'org-cybershield',
    title: 'Outdated Container Base Image Vulnerability Flag',
    framework: 'soc-2',
    controlId: 'SOC2-CC7.2',
    severity: 'medium',
    owner: 'Elena Rostova',
    dueDate: '2026-10-12',
    status: 'open',
    identifiedDate: '2026-09-20',
    whyIdentified: 'Trivy container scan detected CVE-2026-3819 in alpine:3.18 base image.',
    missingInfo: 'Alpine 3.20 upgrade PR build log.',
    recommendedAction: 'Rebase Dockerfile to alpine:3.20 and rebuild ECR container image.',
    relatedEvidenceIds: [],
  }
];

export const mockReviewQueue: ReviewQueueItem[] = [
  // Org 1: Acme
  {
    id: 'rev-201',
    organizationId: 'org-acme',
    evidenceId: 'ev-102',
    evidenceName: 'Okta Adaptive MFA & SSO Enforcement Audit Export',
    evidenceVersion: 'v4.0',
    fileType: 'pdf',
    framework: 'soc-2',
    controlId: 'SOC2-CC6.1',
    controlTitle: 'Logical Access Security Controls',
    aiConfidence: 92,
    aiReasoning: 'AI extracted Okta rule configurations requiring FIDO2 WebAuthn hardware keys and push tokens for all accounts. 100% user match detected.',
    evidenceExcerpt: 'Rule #1: Enforce Multi-Factor Authentication (MFA) on every sign-in attempt. Allowed Authenticators: Okta Verify Push, FIDO2 WebAuthn Key.',
    citations: [
      { page: 4, section: 'Authentication Policies', text: 'Allowed Authenticators: FIDO2 WebAuthn Key' }
    ],
    missingEvidenceList: ['Quarterly Service Account Exemption Approval Matrix'],
    potentialConcerns: 'Ensure legacy service accounts bypass list is audited and explicitly approved by CISO.',
    assignedAuditor: 'David Chen, CPA',
    lastUpdated: '2026-09-23 09:15 AM',
    status: 'pending_review',
    decisionType: 'pending_human_review',
  },
  {
    id: 'rev-202',
    organizationId: 'org-acme',
    evidenceId: 'ev-103',
    evidenceName: 'Q3 Enterprise Penetration Testing Report 2026',
    evidenceVersion: 'v1.0',
    fileType: 'pdf',
    framework: 'iso-27001',
    controlId: 'ISO-A.12.6.1',
    controlTitle: 'Management of Technical Vulnerabilities',
    aiConfidence: 89,
    aiReasoning: 'AI verified penetration test report summary by Bishop Fox confirming zero open critical/high vulnerabilities following Sept 14 re-test.',
    evidenceExcerpt: 'All 3 initial medium findings were verified remediated on Sept 14, 2026 with zero remaining unaddressed vulnerabilities.',
    citations: [
      { page: 18, section: 'Re-test Attestation', text: 'Verified remediated on Sept 14, 2026' }
    ],
    assignedAuditor: 'David Chen, CPA',
    lastUpdated: '2026-09-22 04:45 PM',
    status: 'pending_review',
    decisionType: 'pending_human_review',
  },

  // Org 3: Nexus Health
  {
    id: 'rev-301',
    organizationId: 'org-nexus',
    evidenceId: 'ev-301',
    evidenceName: 'Nexus Health Patient EHR Data Pseudonymization Policy',
    evidenceVersion: 'v1.0',
    fileType: 'pdf',
    framework: 'dpdp',
    controlId: 'DPDP-SEC8',
    controlTitle: 'Data Fiduciary EHR Safeguards',
    aiConfidence: 94,
    aiReasoning: 'Pramana AI verified tokenized field encryption for FHIR API patient health records.',
    evidenceExcerpt: 'Section 3.1 Personal Health Data Encryption: All FHIR API endpoints enforce tokenized field encryption with HSM keys.',
    citations: [
      { page: 5, section: 'Data Pseudonymization Pipeline', text: 'HSM customer-managed key rotation' }
    ],
    assignedAuditor: 'David Chen, CPA',
    lastUpdated: '2026-09-24 09:30 AM',
    status: 'pending_review',
    decisionType: 'pending_human_review',
  }
];

export const mockAuditTrail: AuditTrailLog[] = [
  // Org 1: Acme
  {
    id: 'log-901',
    organizationId: 'org-acme',
    timestamp: '2026-09-24 08:30:14 AM',
    actor: {
      name: 'Aarav Mehta',
      email: 'aarav.mehta@acme.com',
      role: 'Enterprise CISO',
      type: 'user',
    },
    action: 'Evidence Uploaded',
    resourceType: 'Evidence',
    resourceId: 'ev-106',
    resourceName: 'Vendor_SOC2_Type2_Report_Datadog.pdf',
    framework: 'soc-2',
    details: 'Uploaded vendor SOC 2 Type II report for Datadog. AI analysis triggered automatically.',
    ipAddress: '192.168.1.104 (TLS 1.3 encrypted)',
    integrityVerified: true,
    sha256Hash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
  },
  {
    id: 'log-902',
    organizationId: 'org-acme',
    timestamp: '2026-09-24 08:30:45 AM',
    actor: {
      name: 'Pramana AI Engine v4.2',
      email: 'ai-engine@pramana.internal',
      role: 'AI Analysis Service',
      type: 'ai',
    },
    action: 'AI Control Mapping Generated',
    resourceType: 'Control',
    resourceId: 'SOC2-CC9.2',
    resourceName: 'Vendor Risk Management & Monitoring',
    framework: 'soc-2',
    details: 'AI parsed Datadog SOC2 document. Confidence score: 91%. Mapped to SOC2-CC9.2 and ISO-A.15.1.1.',
    previousState: 'Unmapped',
    newState: 'AI Suggested Mapping (Pending Human Review)',
    ipAddress: '10.0.4.12 (Internal RPC)',
    integrityVerified: true,
    sha256Hash: '9a31bc40212f8832a514d28471209b5523a1012398572eab748234190b',
  },

  // Org 2: CyberShield
  {
    id: 'log-903',
    organizationId: 'org-cybershield',
    timestamp: '2026-09-19 03:20:00 PM',
    actor: {
      name: 'David Chen, CPA',
      email: 'david.chen@auditfirm-partner.com',
      role: 'External Auditor',
      type: 'auditor',
    },
    action: 'Auditor Decision Approved',
    resourceType: 'Control',
    resourceId: 'ISO-A.9.2.1',
    resourceName: 'Zero Trust Access Provisioning',
    framework: 'iso-27001',
    details: 'Auditor verified CyberShield Zero Trust architecture.',
    ipAddress: '203.0.113.45',
    integrityVerified: true,
    sha256Hash: 'f482a4918c502b1849a941e739487c50a12b489a',
  }
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    organizationId: 'org-acme',
    title: '4 Items Awaiting Auditor Review',
    description: 'AI mappings for Okta MFA and Penetration Testing reports require auditor sign-off.',
    timestamp: '15 mins ago',
    read: false,
    type: 'review_required',
    linkTarget: 'review-queue',
  },
  {
    id: 'notif-2',
    organizationId: 'org-acme',
    title: 'High Priority Gap Identified',
    description: 'Unencrypted staging S3 buckets detected in ISO 27001 audit scope.',
    timestamp: '2 hours ago',
    read: false,
    type: 'gap_alert',
    linkTarget: 'gaps',
  },
];
